version: '3.8'

services:
  vggt:
    build:
      context: .
      dockerfile: Dockerfile
    image: vggt:latest
    container_name: vggt-dev
    
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Mount volumes
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ~/.cache/huggingface
        target: /root/.cache/huggingface  # Cache HuggingFace models
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Increase shared memory size for PyTorch DataLoader
    shm_size: '16gb'

    # Network settings
    network_mode: host
    
    # Expose ports for demos
    ports:
      - "7860:7860"  # Gradio demo
      - "8080:8080"  # Viser demo
    
    working_dir: /workspace
    
    # Use bash as default
    command: /bin/bash
